### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ihollander** [charliepatronr/mod-1-mini-challenge-enumerables#1]
Great job overall using the different enumerable methods, it looks like you have a good handle on the syntax! Just a couple pieces of feedback:

- Make sure you are using proper indentation everywhere, it takes practice but the sooner you develop good habits, the better! It makes it much easier to read and debug your code if you can easily see where a method begins and end as well as where a block begins and ends.

- there are a couple places where you have variable assignments that aren't necessary, make sure you are only assigning data to variables if you plan on referring to those variables somewhere else in your code. For example:

```rb
def print_spicy_foods(spicy_foods)
  spicy_foods.each do |food|
    # food_item = ... creates a local variable, but you aren't using this variable anywhere
    p food_item = "" #{food[:name]} (#{food[:cuisine]}) | Heat Level: #{food[:heat_level]}""
    
    # instead, you could just do:
    # puts ""#{food[:name]} (#{food[:cuisine]}) | Heat Level: #{food[:heat_level]}""
  end 
end
```

- for the `average_heat_level` method, your code works great, but if you want to know another useful enumerable method, here's how you could have written this using `sum`:

```rb
total_heat_level = spicy_foods.sum do |spicy_food_hash|
  # when used with a block, 
  # sum will total up the values returned in the block
  spicy_food_hash[:heat_level]
end

total_heat_level.to_f / spicy_foods.length
```

**Comment by charliepatronr** [comment]
Thanks a lot Ian! I'll check the indentation, sorry about the assigning of unnecessary variables, I'm sorta used to javascript that does not have an implicit return. 
Also thanks for the sum method! I also noticed I forgot the to_f method.
